---
name: turbulence

director_uuid: 1814d7a5-6a04-4201-adb1-d6e38cb4fb14

releases:
- {name: turbulence, version: latest}
- {name: bosh-warden-cpi, version: latest}

jobs:
- name: api
  templates:
  - {name: turbulence_api, release: turbulence}
  - {name: cpi, release: bosh-warden-cpi}
  instances: 1
  resource_pool: default
  networks:
  - {name: default, static_ips: [10.244.8.2]}

properties:
  turbulence_api:
    password: p
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDDjCCAfagAwIBAgIJANy2vEpugwXuMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
      BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
      aWRnaXRzIFB0eSBMdGQwIBcNMTUwNzEzMDYwNjM2WhgPMjI4OTA0MjYwNjA2MzZa
      MDExCzAJBgNVBAYTAlVTMQ0wCwYDVQQKEwRCT1NIMRMwEQYDVQQDEwoxMC4yNDQu
      OC4yMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzXtIoK2JThldtokn
      HD5hQ9qL+JL4/viZTaQ63Y+lpRsjHCGiQcQoWti4ah8akct8HfIOX9ECfsbLOJet
      VYzXPqrgJjxPFVO92b087uncIsJ0cBGOu0QFtT3R8d5eFvcdqgJICFcW7NEZ9pA6
      KcZxEOcgkgx2G5ktblOz5frwBKcpAm5amKC+7YpcO+VvA/6ZoBiJIMg8JHOmRgtQ
      cItD+ll+8FN+C81aWhrB2GNu5NslN/PE4N93tCwbOxXoQh3IJjn6NfAeCo0Rhc1l
      BnLZ0YflZkKfXTHGnUeyDyWqv4DECAXZy+jQRN+z3TnRYCtEu5xKsIbDLfHRa6jd
      vkBK+wIDAQABoxMwETAPBgNVHREECDAGhwQK9AgCMA0GCSqGSIb3DQEBBQUAA4IB
      AQAuEA9wpw51Noj4JiNW3nHugbgxP2ZorenM4lubKkyM9E1Dg6eFUaKe66R31q/r
      u4+9Cx7gH5umhAzffjszALPg3cUnCqo6GeRHdLctRFOSE6fpGUZQp/6cc6Ki9Tl6
      vRzBZPDasSciLu2m2flfkKs6PVrMaJTrh976GYUEoYp6MnypKko6mq9aXRGynp1J
      C7e1Ff4DVUG5SIfof1R0o/jIWAan8IcoeTnD8+UycpYH2tiNkzcx1jqw/DKwzEGr
      80LnwDW3hunapDlMTJaGDT03q595IMESJ6UmlbX+W4x0WzIvpuOsSrSTiBuY/u6L
      76PlccVikz6q+IXCXtcts0CL
      -----END CERTIFICATE-----
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAzXtIoK2JThldtoknHD5hQ9qL+JL4/viZTaQ63Y+lpRsjHCGi
      QcQoWti4ah8akct8HfIOX9ECfsbLOJetVYzXPqrgJjxPFVO92b087uncIsJ0cBGO
      u0QFtT3R8d5eFvcdqgJICFcW7NEZ9pA6KcZxEOcgkgx2G5ktblOz5frwBKcpAm5a
      mKC+7YpcO+VvA/6ZoBiJIMg8JHOmRgtQcItD+ll+8FN+C81aWhrB2GNu5NslN/PE
      4N93tCwbOxXoQh3IJjn6NfAeCo0Rhc1lBnLZ0YflZkKfXTHGnUeyDyWqv4DECAXZ
      y+jQRN+z3TnRYCtEu5xKsIbDLfHRa6jdvkBK+wIDAQABAoIBADuVkE3nhHU9LcuM
      oeaywAmpCgWeuM1W0T2ObfNpgCMMZ3X02tQvSXRue6tqMY4tb2RPmJN4TDzu8GcM
      tJqmKJRngHAV9Oi+S8Mj+NNexRLfSFxm+vialP0lXAfC743BQrzVxIWGm4M4b0rs
      L7GFdavtGajALE98b4wagYQi7A6s1NduBsMGjjzk6kl18mgYUsBNF/Wxg0nxhDbN
      XCP7o0Ih9xR63DLMWbm7a7hz9Xfxp7lhVRAb8TO76ehkqyKWL2BPMFJzJGImsdRQ
      JPLMG6nD9cTeY5hHa5tW7w+9IEHf6WRpBg2NpOSgKVGA0Nk+iQd4mONXycM0K71Y
      lehXhMECgYEA+iIii255BohUpGyS3FNbh6zntez+qYaGVq1VRiWz+FZ4cjgxM0OV
      WfA1/CnDK8uavIvWlA6R5z4sEaxR3w+zY7tjmej+5b/YgJjivaP2A2im2LRn22yn
      uV7OMPJFS66/fKpYks84VKm7CcY9dY2StvVbHqkWFsBER/5Z0mFpbOkCgYEA0k0M
      ThmKlE0HEOamogTtf6XsjR3Ie1i62NVPB4a1W/FmnDtQWnCY0rFGEOexXwL0pz5y
      dIiTs+uqnCuV6whC0L5Eqr7OGofgGqousQtKQwNr9518CDpRoyoSjgJBalctpe1M
      JW/Xn4QDVpob9OCq84h7eA8wsvY/CUWXoqecOkMCgYB9tbQY0S+f+dpYPHzeoEIr
      ANn/E5m1R3eyjjCCLaayU3r7JISNmBSye8gV8EM3en9M7RatmFj5l8R8KVeIPJLS
      t7XJ/1BD1VQQ5UVnO8UDV5Aq7xgXLhdpUV1dOhVbgPqZw976AYz098yZj/kJYFpw
      +wSNdzszufNXH1yzH+PlKQKBgQCfZFZXO3SVQmyAmtDhK+r2PMQ1kMVK981mWwYz
      Jh5/OVAUScB1S7IIvuPkHDeLU6oquGH3gSyxyYTeKQrPwMsje5J/924vHZz1mNca
      yPvYHtfOLUa81bbafCDkEUGTX8/xWxHDrik3dc8x7EwUJdRsEJ3EOX8npQvR8zUi
      yvbWEQKBgEi3ry1V0JnC6plR0TkhVTydxGvg17Iiz/WWzOEPUTY5aFse9xuNVUOZ
      aCZyPyQHIoXgiW0NgCG9vOzqRaH2A99UIX2++rBHVrNkRcoxEQkH4kw+slX2W3Jo
      ppdcmP6zyOneqvyAbjG4KRwqg6V2Phd3Tub8zcJOx7wU5V3Ljs87
      -----END RSA PRIVATE KEY-----

    director:
      host: 192.168.50.4
      port: 25555
      ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDtzCCAp+gAwIBAgIJAL+XoGqlINOLMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
        BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQwIBcNMTUwNzEyMDIzNTA4WhgPMjI4OTA0MjUwMjM1MDha
        MEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJ
        bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
        ggEKAoIBAQDOGrPb3jitQZBPqJYC2/1rrpXO6cQF4hQV6CPajFnTYI2TmoKVrPpt
        hbJVbcWC4VopmfVrq2YLkP28L25QEtNCg8QBJOa5jLPCDzffasA40YUqrMMWOh0b
        JqzXKgtc4u0FffHBSXq3csyQXNeB/UG6qk/0YuJCFYY5zVAnOmyKdLJjngmUQovx
        ssjfcprkgOMqpPW9BSus4m945OEWqQixk0saxT1MTL3do7oGSacT30jXZV9bowlV
        COsZj+rR6IQkNYaZUWfYBPuHzEP3RN/J21F7T0KCi4q49CnkEwVsf6pnjFhIBuJ7
        u+vKQ3Gq0Yro28SJs0leE8x3OA/WnLiJAgMBAAGjgacwgaQwHQYDVR0OBBYEFNL4
        IU9fUeXBlqKwczeB3Pnup8qeMHUGA1UdIwRuMGyAFNL4IU9fUeXBlqKwczeB3Pnu
        p8qeoUmkRzBFMQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8G
        A1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkggkAv5egaqUg04swDAYDVR0T
        BAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAMgANBnQbsgs9Yr0wSG1jD4w/pM90
        y7MkLjstmOC5u9kHihWk3KDoI4Bx0fXD9wbyhP/E9AikqG7SglkuViRCrtWDprEp
        8kTGbPG8sPjiu2cnmG19QcmL4HHHaG76r75qEggPu2wRGlEj0BR2zwOuINHCjfgz
        Zi8Gl/4jRAazOcXmFfnNy/RXVOwswWQOG7aKbhHWCODn7jobT95wVTouEppUw7p9
        twzPSzG7vudrmO3PSgAT+db/xrDRoHa3xk5H3fltZi7uxpRaWPqsFDezDYul4C8b
        9JpGUkpLi0wGcVfceVLiZooxVGIQTFJj8Yu6fnTM2ZbD0xwFDyrYM92uWg==
        -----END CERTIFICATE-----
      username: admin
      password: admin

  cpi:
    # no host_ip
    warden:
      connect_network: tcp
      connect_address: 10.254.50.4:7777
    agent:
      mbus: nats://nats:nats-password@10.254.50.4:4222
      blobstore:
        provider: dav
        options:
          endpoint: http://10.254.50.4:25251
          user: agent
          password: agent-password

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.8.0/30
    reserved: [10.244.8.1]
    static: [10.244.8.2]
    cloud_properties: {}
- name: compilation
  type: dynamic
  cloud_properties: {}

compilation:
  workers: 5
  network: compilation
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000 - 20000
  update_watch_time: 5000 - 20000
