---
name: dummy

releases:
- name: turbulence
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: dummy_z1
  instances: 5
  azs: [z1, z2]
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api: {from: api, deployment: turbulence}
  vm_type: default
  stemcell: default
  networks:
  - name: default

- name: dummy_z2
  instances: 1
  azs: [z1, z2]
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api: {from: api, deployment: turbulence}
  vm_type: default
  stemcell: default
  networks:
  - name: default

update:
  canaries: 0
  max_in_flight: 4
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
